<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProjectProcess extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable=[
        'user_id',
        'description',
    ];

    public function steps(){
        return $this->hasMany(ProcessStep::class,'process_id');
    }
    public function order(){
        return $this->morphOne(OrderProduct::class, 'order_model');
    }
    public function user(){
        return $this->belongsTo(User::class,'user_id','id');
    }

    protected static function boot()
    {
        self::updated(function ($query){
            if ($query->isDirty('requires_invoice')){

            }
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }


}
